import './js/on-load';
import './js/get-genres';
import './js/add-to-queue';
import './js/add-to-watched';
import './js/add-local';
import './js/trailer';
import './js/modal-btn-add-local';
import './js/popular-movies';
// import './js/api-key';
import './js/get-refs';
import './js/search-movies';
import './js/movie-modal';
import './js/spiner';
import './js/themoviedb-api-class';
// import './js/pagination';
import './templates/card_film.hbs';
import './js/teamModal';
import './js/pagination-popular';
import './js/pagination-search';
import './js/handlebars-helper';
