import './js/lib';
import './js/add-to-queue';
import './js/add-to-watched';
import './js/add-local';
import './js/get-refs';
import './js/spiner';
import './js/movie-modal'
import './js/modal-btn-add-local'
import './js/pagination-library';
import './js/pagination-library-queue';